/**
 * Protocol PDF Document
 * Professional PDF export for IRB submissions, archiving, and PI review
 *
 * Sections:
 * 1. Cover Page
 * 2. SPECTRA Summary
 * 3. Foundational Papers Synthesis
 * 4. Schema Definition
 * 5. Statistical Analysis Plan
 */

import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  Link,
} from '@react-pdf/renderer';
import { styles, colors } from './styles';
import type { SPECTRAContext } from '../../ai-personas/statistician/spectra/types';
import type { SavedProtocol, ProtocolVersion, SchemaBlock } from '../../protocol-workbench/types';
import type { FoundationalPaperExtraction } from '../../../services/geminiService';

// =============================================================================
// TYPES
// =============================================================================

export interface ProtocolPDFData {
  protocol: SavedProtocol;
  version: ProtocolVersion;
  spectra?: SPECTRAContext;
  foundationalPapers?: FoundationalPaperExtraction[];
  picoFields?: {
    population?: string;
    intervention?: string;
    comparison?: string;
    outcome?: string;
    timeframe?: string;
  };
  generatedAt: string;
}

// =============================================================================
// HELPER COMPONENTS
// =============================================================================

const PageHeader: React.FC<{ title: string; protocolNumber: string }> = ({
  title,
  protocolNumber,
}) => (
  <View style={styles.pageHeader}>
    <Text style={styles.pageHeaderTitle}>{title}</Text>
    <Text style={styles.pageHeaderProtocol}>{protocolNumber}</Text>
  </View>
);

const PageFooter: React.FC<{ protocolNumber: string }> = ({ protocolNumber }) => (
  <View style={styles.footer} fixed>
    <Text style={styles.footerText}>
      {protocolNumber} • Generated by Spectra XR Clinical Intelligence Engine
    </Text>
    <Text
      style={styles.pageNumber}
      render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
    />
  </View>
);

const SectionTitle: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Text style={styles.sectionTitle}>{children}</Text>
);

const SubsectionTitle: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Text style={styles.subsectionTitle}>{children}</Text>
);

const LabelValue: React.FC<{ label: string; value?: string | null }> = ({
  label,
  value,
}) => (
  <View style={{ marginBottom: 8 }}>
    <Text style={styles.label}>{label}</Text>
    <Text style={styles.value}>{value || 'Not specified'}</Text>
  </View>
);

const ListItem: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <View style={styles.listItem}>
    <Text style={styles.listBullet}>•</Text>
    <Text style={styles.listContent}>{children}</Text>
  </View>
);

const InfoCard: React.FC<{
  title: string;
  children: React.ReactNode;
  variant?: 'default' | 'primary' | 'secondary' | 'accent';
}> = ({ title, children, variant = 'default' }) => {
  const cardStyle =
    variant === 'primary'
      ? styles.cardPrimary
      : variant === 'secondary'
      ? styles.cardSecondary
      : variant === 'accent'
      ? styles.cardAccent
      : styles.card;

  return (
    <View style={cardStyle}>
      <Text style={[styles.subsectionTitle, { marginTop: 0 }]}>{title}</Text>
      {children}
    </View>
  );
};

// =============================================================================
// COVER PAGE
// =============================================================================

const CoverPage: React.FC<{ data: ProtocolPDFData }> = ({ data }) => {
  const { protocol, version, generatedAt } = data;
  const metadata = version.metadata;

  return (
    <Page size="A4" style={styles.coverPage}>
      {/* Logo placeholder */}
      <View
        style={{
          width: 60,
          height: 60,
          backgroundColor: colors.primary,
          borderRadius: 8,
          marginBottom: 30,
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <Text style={{ color: 'white', fontSize: 24, fontFamily: 'Helvetica-Bold' }}>
          S
        </Text>
      </View>

      <Text style={styles.coverTitle}>{protocol.protocolTitle || 'Untitled Protocol'}</Text>
      <Text style={styles.coverSubtitle}>Clinical Research Protocol Document</Text>

      <Text style={styles.coverProtocolNumber}>{protocol.protocolNumber || 'Draft'}</Text>

      <View style={styles.coverMetaContainer}>
        <View style={styles.coverMetaRow}>
          <Text style={styles.coverMetaLabel}>Principal Investigator</Text>
          <Text style={styles.coverMetaValue}>
            {metadata?.principalInvestigator || 'Not assigned'}
          </Text>
        </View>
        <View style={styles.coverMetaRow}>
          <Text style={styles.coverMetaLabel}>Sponsor</Text>
          <Text style={styles.coverMetaValue}>{metadata?.sponsor || 'Not specified'}</Text>
        </View>
        <View style={styles.coverMetaRow}>
          <Text style={styles.coverMetaLabel}>Study Phase</Text>
          <Text style={styles.coverMetaValue}>{metadata?.studyPhase || 'Not specified'}</Text>
        </View>
        <View style={styles.coverMetaRow}>
          <Text style={styles.coverMetaLabel}>Therapeutic Area</Text>
          <Text style={styles.coverMetaValue}>
            {metadata?.therapeuticArea || 'Not specified'}
          </Text>
        </View>
        <View style={styles.coverMetaRow}>
          <Text style={styles.coverMetaLabel}>Version</Text>
          <Text style={styles.coverMetaValue}>
            {version.versionNumber} ({version.status})
          </Text>
        </View>
        <View style={styles.coverMetaRow}>
          <Text style={styles.coverMetaLabel}>Generated</Text>
          <Text style={styles.coverMetaValue}>
            {new Date(generatedAt).toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })}
          </Text>
        </View>
      </View>

      <Text style={styles.coverFooter}>
        Confidential • For authorized use only{'\n'}
        Generated by Spectra XR Clinical Intelligence Engine
      </Text>
    </Page>
  );
};

// =============================================================================
// SPECTRA SUMMARY PAGE
// =============================================================================

const SPECTRAPage: React.FC<{ data: ProtocolPDFData }> = ({ data }) => {
  const { protocol, spectra, picoFields } = data;

  return (
    <Page size="A4" style={styles.page}>
      <PageHeader title="SPECTRA Framework Summary" protocolNumber={protocol.protocolNumber} />

      {/* PICO Summary if no full SPECTRA */}
      {picoFields && !spectra && (
        <>
          <SectionTitle>PICO Framework</SectionTitle>
          <View style={styles.row}>
            <View style={styles.col2}>
              <LabelValue label="Population" value={picoFields.population} />
            </View>
            <View style={styles.col2}>
              <LabelValue label="Intervention" value={picoFields.intervention} />
            </View>
          </View>
          <View style={styles.row}>
            <View style={styles.col2}>
              <LabelValue label="Comparison" value={picoFields.comparison} />
            </View>
            <View style={styles.col2}>
              <LabelValue label="Outcome" value={picoFields.outcome} />
            </View>
          </View>
          {picoFields.timeframe && (
            <LabelValue label="Timeframe" value={picoFields.timeframe} />
          )}
        </>
      )}

      {/* Full SPECTRA Context */}
      {spectra && (
        <>
          {/* Study Design */}
          <InfoCard title="Study Design" variant="primary">
            <View style={styles.row}>
              <View style={styles.col2}>
                <LabelValue
                  label="Design Type"
                  value={spectra.study.designType?.replace(/-/g, ' ').toUpperCase()}
                />
              </View>
              <View style={styles.col2}>
                <LabelValue label="Phase" value={spectra.study.phase || 'N/A'} />
              </View>
            </View>
            {spectra.study.randomization && (
              <View style={styles.row}>
                <View style={styles.col2}>
                  <LabelValue
                    label="Randomization"
                    value={`${spectra.study.randomization.method} (${spectra.study.randomization.allocationRatio || '1:1'})`}
                  />
                </View>
                <View style={styles.col2}>
                  <LabelValue
                    label="Blinding"
                    value={spectra.study.blinding?.level?.replace(/-/g, ' ')}
                  />
                </View>
              </View>
            )}
          </InfoCard>

          {/* Population */}
          <InfoCard title="Population">
            <Text style={styles.paragraph}>
              {spectra.population.targetPopulation || 'Not specified'}
            </Text>
            {spectra.population.targetEnrollment && (
              <LabelValue
                label="Target Enrollment"
                value={`N = ${spectra.population.targetEnrollment}`}
              />
            )}
            {spectra.population.stratificationFactors &&
              spectra.population.stratificationFactors.length > 0 && (
                <>
                  <Text style={[styles.label, { marginTop: 8 }]}>Stratification Factors</Text>
                  {spectra.population.stratificationFactors.map((f, i) => (
                    <ListItem key={i}>{f.name}</ListItem>
                  ))}
                </>
              )}
          </InfoCard>

          {/* Endpoints */}
          <InfoCard title="Endpoints" variant="secondary">
            {spectra.endpoints.primary.length > 0 && (
              <>
                <Text style={[styles.label, { color: colors.secondary }]}>Primary Endpoints</Text>
                {spectra.endpoints.primary.map((ep, i) => (
                  <View key={i} style={{ marginBottom: 6 }}>
                    <Text style={[styles.value, styles.bold]}>{ep.name}</Text>
                    <Text style={[styles.value, { fontSize: 9, color: colors.textMuted }]}>
                      Type: {ep.type} • Direction: {ep.direction?.replace(/-/g, ' ')}
                      {ep.unit && ` • Unit: ${ep.unit}`}
                    </Text>
                  </View>
                ))}
              </>
            )}
            {spectra.endpoints.secondary.length > 0 && (
              <>
                <Text style={[styles.label, { marginTop: 10 }]}>Secondary Endpoints</Text>
                {spectra.endpoints.secondary.map((ep, i) => (
                  <ListItem key={i}>{ep.name}</ListItem>
                ))}
              </>
            )}
          </InfoCard>

          {/* Comparator */}
          {spectra.comparator.arms.length > 0 && (
            <InfoCard title="Treatment Arms">
              {spectra.comparator.arms.map((arm, i) => (
                <View key={i} style={styles.row}>
                  <View style={{ width: 100 }}>
                    <Text style={[styles.value, styles.bold]}>{arm.name}</Text>
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={styles.value}>
                      {arm.type?.replace(/-/g, ' ')}
                      {arm.targetN && ` (n=${arm.targetN})`}
                    </Text>
                  </View>
                </View>
              ))}
              {spectra.comparator.allocationRatio && (
                <LabelValue
                  label="Allocation Ratio"
                  value={spectra.comparator.allocationRatio}
                />
              )}
            </InfoCard>
          )}

          {/* Analysis Parameters */}
          <InfoCard title="Analysis Parameters" variant="accent">
            <View style={styles.row}>
              <View style={styles.col3}>
                <LabelValue label="Alpha" value={spectra.analysisParameters.alpha?.toString()} />
              </View>
              <View style={styles.col3}>
                <LabelValue
                  label="Power"
                  value={
                    spectra.analysisParameters.power
                      ? `${(spectra.analysisParameters.power * 100).toFixed(0)}%`
                      : undefined
                  }
                />
              </View>
              <View style={styles.col3}>
                <LabelValue
                  label="Effect Size"
                  value={
                    spectra.analysisParameters.effectSize
                      ? `${spectra.analysisParameters.effectSize.value} (${spectra.analysisParameters.effectSize.type})`
                      : 'Not specified'
                  }
                />
              </View>
            </View>
            {spectra.analysisParameters.populations.length > 0 && (
              <>
                <Text style={[styles.label, { marginTop: 8 }]}>Analysis Populations</Text>
                {spectra.analysisParameters.populations.map((pop, i) => (
                  <ListItem key={i}>
                    {pop.name} ({pop.type}){pop.isPrimary && ' - Primary'}
                  </ListItem>
                ))}
              </>
            )}
          </InfoCard>
        </>
      )}

      <PageFooter protocolNumber={protocol.protocolNumber} />
    </Page>
  );
};

// =============================================================================
// FOUNDATIONAL PAPERS PAGE
// =============================================================================

const FoundationalPapersPage: React.FC<{ data: ProtocolPDFData }> = ({ data }) => {
  const { protocol, foundationalPapers } = data;

  if (!foundationalPapers || foundationalPapers.length === 0) {
    return null;
  }

  return (
    <Page size="A4" style={styles.page}>
      <PageHeader title="Foundational Literature" protocolNumber={protocol.protocolNumber} />

      <SectionTitle>Literature Synthesis</SectionTitle>
      <Text style={styles.paragraph}>
        The following foundational papers inform the study design, methodology, and expected
        outcomes for this protocol. These references were extracted and analyzed to provide
        evidence-based guidance for the statistical analysis plan.
      </Text>

      {foundationalPapers.map((paper, index) => (
        <View key={index} style={styles.card}>
          <Text style={[styles.subsectionTitle, { marginTop: 0, color: colors.primary }]}>
            {index + 1}. {paper.title}
          </Text>
          <Text style={[styles.value, { fontStyle: 'italic', marginBottom: 8 }]}>
            {paper.authors} ({paper.year})
          </Text>

          {paper.doi && (
            <Text style={[styles.value, { fontSize: 9, color: colors.primaryLight }]}>
              DOI: {paper.doi}
            </Text>
          )}

          <View style={styles.divider} />

          <View style={styles.row}>
            {paper.sampleSize && (
              <View style={styles.col2}>
                <LabelValue label="Sample Size" value={`N = ${paper.sampleSize}`} />
              </View>
            )}
            {paper.studyDesign && (
              <View style={styles.col2}>
                <LabelValue label="Study Design" value={paper.studyDesign} />
              </View>
            )}
          </View>

          {paper.statisticalMethods && paper.statisticalMethods.length > 0 && (
            <>
              <Text style={styles.label}>Statistical Methods</Text>
              <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginTop: 4 }}>
                {paper.statisticalMethods.map((method, i) => (
                  <Text
                    key={i}
                    style={{
                      fontSize: 8,
                      backgroundColor: colors.primaryBg,
                      color: colors.primary,
                      paddingVertical: 2,
                      paddingHorizontal: 6,
                      borderRadius: 4,
                      marginRight: 4,
                      marginBottom: 4,
                    }}
                  >
                    {method}
                  </Text>
                ))}
              </View>
            </>
          )}

          {paper.relevance && (
            <>
              <Text style={[styles.label, { marginTop: 8 }]}>Relevance to Protocol</Text>
              <Text style={styles.paragraph}>{paper.relevance}</Text>
            </>
          )}
        </View>
      ))}

      <PageFooter protocolNumber={protocol.protocolNumber} />
    </Page>
  );
};

// =============================================================================
// SCHEMA PAGE
// =============================================================================

/**
 * Flatten nested schema blocks to get all fields including those in sections
 */
const flattenSchemaBlocks = (blocks: SchemaBlock[]): SchemaBlock[] => {
  const result: SchemaBlock[] = [];

  const processBlock = (block: SchemaBlock) => {
    // Add non-section blocks to result
    if (block.dataType !== 'Section') {
      result.push(block);
    }
    // Recurse into children
    if (block.children && block.children.length > 0) {
      block.children.forEach(processBlock);
    }
  };

  blocks.forEach(processBlock);
  return result;
};

const SchemaPage: React.FC<{ data: ProtocolPDFData }> = ({ data }) => {
  const { protocol, version } = data;
  const schemaBlocks = version.schemaBlocks || [];

  // Flatten nested blocks to get all variables (including those inside sections)
  const variables = flattenSchemaBlocks(schemaBlocks);
  const predictors = variables.filter((b) => b.role === 'Predictor');
  const outcomes = variables.filter((b) => b.role === 'Outcome');
  const structural = variables.filter((b) => b.role === 'Structure' || b.role === 'All');

  const primaryEndpoints = outcomes.filter((b) => b.endpointTier === 'primary');
  const secondaryEndpoints = outcomes.filter((b) => b.endpointTier === 'secondary');
  const exploratoryEndpoints = outcomes.filter((b) => b.endpointTier === 'exploratory');

  const renderVariableTable = (
    blocks: SchemaBlock[],
    title: string,
    showEndpointTier = false
  ) => {
    if (blocks.length === 0) return null;

    return (
      <>
        <SubsectionTitle>{title}</SubsectionTitle>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableHeaderCell, { flex: 2 }]}>Variable</Text>
            <Text style={styles.tableHeaderCell}>Type</Text>
            <Text style={styles.tableHeaderCell}>Category</Text>
            {showEndpointTier && <Text style={styles.tableHeaderCell}>Tier</Text>}
            <Text style={styles.tableHeaderCell}>Unit</Text>
          </View>
          {blocks.map((block, index) => (
            <View
              key={block.id}
              style={index % 2 === 0 ? styles.tableRow : styles.tableRowAlt}
            >
              <Text style={[styles.tableCellBold, { flex: 2 }]}>
                {block.customName || block.variable?.name || block.id}
              </Text>
              <Text style={styles.tableCell}>{block.dataType}</Text>
              <Text style={styles.tableCell}>{block.variable?.category || '-'}</Text>
              {showEndpointTier && (
                <Text style={styles.tableCell}>
                  {block.endpointTier || '-'}
                </Text>
              )}
              <Text style={styles.tableCell}>{block.unit || '-'}</Text>
            </View>
          ))}
        </View>
      </>
    );
  };

  return (
    <Page size="A4" style={styles.page}>
      <PageHeader title="Data Collection Schema" protocolNumber={protocol.protocolNumber} />

      <SectionTitle>Schema Overview</SectionTitle>

      <View style={styles.row}>
        <View style={styles.col3}>
          <View style={styles.cardPrimary}>
            <Text style={[styles.label, { textAlign: 'center' }]}>Total Variables</Text>
            <Text
              style={{
                fontSize: 24,
                fontFamily: 'Helvetica-Bold',
                color: colors.primary,
                textAlign: 'center',
              }}
            >
              {variables.length}
            </Text>
          </View>
        </View>
        <View style={styles.col3}>
          <View style={styles.cardSecondary}>
            <Text style={[styles.label, { textAlign: 'center' }]}>Outcome Variables</Text>
            <Text
              style={{
                fontSize: 24,
                fontFamily: 'Helvetica-Bold',
                color: colors.secondary,
                textAlign: 'center',
              }}
            >
              {outcomes.length}
            </Text>
          </View>
        </View>
        <View style={styles.col3}>
          <View style={styles.cardAccent}>
            <Text style={[styles.label, { textAlign: 'center' }]}>Predictor Variables</Text>
            <Text
              style={{
                fontSize: 24,
                fontFamily: 'Helvetica-Bold',
                color: colors.accent,
                textAlign: 'center',
              }}
            >
              {predictors.length}
            </Text>
          </View>
        </View>
      </View>

      {/* Endpoints by tier */}
      {primaryEndpoints.length > 0 && (
        <View style={styles.infoBox}>
          <Text style={[styles.label, { color: colors.primary }]}>Primary Endpoints</Text>
          {primaryEndpoints.map((ep, i) => (
            <Text key={i} style={[styles.value, styles.bold]}>
              {ep.customName || ep.variable?.name} ({ep.dataType})
            </Text>
          ))}
        </View>
      )}

      {renderVariableTable(outcomes, 'Outcome Variables', true)}
      {renderVariableTable(predictors, 'Predictor Variables')}
      {renderVariableTable(structural, 'Structural Variables')}

      <PageFooter protocolNumber={protocol.protocolNumber} />
    </Page>
  );
};

// =============================================================================
// STATISTICAL PLAN PAGE
// =============================================================================

const StatisticalPlanPage: React.FC<{ data: ProtocolPDFData }> = ({ data }) => {
  const { protocol, version } = data;
  const statisticalPlan = version.protocolContent?.statisticalPlan;

  if (!statisticalPlan) {
    return null;
  }

  return (
    <Page size="A4" style={styles.page}>
      <PageHeader title="Statistical Analysis Plan" protocolNumber={protocol.protocolNumber} />

      <SectionTitle>Analysis Plan</SectionTitle>
      <Text style={styles.paragraph}>{statisticalPlan}</Text>

      <PageFooter protocolNumber={protocol.protocolNumber} />
    </Page>
  );
};

// =============================================================================
// MAIN DOCUMENT
// =============================================================================

export const ProtocolPDFDocument: React.FC<{ data: ProtocolPDFData }> = ({ data }) => {
  return (
    <Document
      title={`${data.protocol.protocolNumber || 'Protocol'} - Clinical Research Protocol`}
      author="Spectra XR Clinical Intelligence Engine"
      subject="Clinical Research Protocol Document"
      keywords="clinical trial, research protocol, SPECTRA"
      creator="Spectra XR"
      producer="@react-pdf/renderer"
    >
      <CoverPage data={data} />
      <SPECTRAPage data={data} />
      <FoundationalPapersPage data={data} />
      <SchemaPage data={data} />
      <StatisticalPlanPage data={data} />
    </Document>
  );
};

export default ProtocolPDFDocument;
